# This is the environment configuration
# to be used in AWS SageMaker Studio Lab
# You can right-click install this from
# JupyterLab inside AWS SMS Lab.
# To use:
#   $ conda env create -f environment.yml
#   $ conda activate wildcatter
name: wildcatter-ThreeAmigos
dependencies:
  - python=3.9
  - pip
  - pip:
      - --editable .
      - ipykernel
      - numpy
      - gym
      - sb3_contrib
      - tensorflow
      - ray
